### ISSUE TITLE
Build fails on OpenBSD

### ISSUE THREAD

**Issue by margaretjoanmiller** [alexcrichton/openssl-sys#4]
Howdy! I'm trying to build this project on OpenBSD but I'm getting an odd error:
```
error: failed to run custom build command for `openssl-sys v0.9.45`

Caused by:
  process didn't exit successfully: `/tmp/cargo-install0xvzuk/release/build/openssl-sys-ba87a9adac352fdf/build-script-main` (exit code: 101)
--- stdout
cargo:rustc-cfg=const_fn

--- stderr
thread 'main' panicked at 'don't know how to configure OpenSSL for x86_64-unknown-openbsd', /home/gigavinyl/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.6.1+1.1.1d/src/lib.rs:180:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-web v0.6.26`, intermediate artifacts can be found at `/tmp/cargo-install0xvzuk`

Caused by:
  build failed
```

**Comment by alexcrichton** [comment]
Thanks for the report! This crate doesn't support openbsd at this time but PRs are welcome!

**Comment by rzr** [comment]
Hi,
Same issue for unsuported linux OS, may it fallback to well known locations ?

yocto  "OpenSSL for x86_64-oe-linux" I can give more details:

```
|   thread 'main' panicked at 'don't know how to configure OpenSSL for x86_64-oe-linux', .../oniro/build-oniro-linux/tmp-glibc/work/core2-64-oe-linux/astarte/sdk.AUTOINC+e302810d05-0.1.0/cargo_home/bitbake/openssl-src-300.0.2+3.0.0/src/lib.rs:296:18
|   stack backtrace:
|      0: rust_begin_unwind
|      1: std::panicking::begin_panic_fmt
|      2: openssl_src::Build::build
|      3: build_script_main::find_vendored::get_openssl
|      4: build_script_main::find_openssl
|      5: build_script_main::main
|      6: core::ops::function::FnOnce::call_once
|   note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Related-to: https://github.com/meta-rust/meta-rust/issues/361
